# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-07 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetEntryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('date_of_expenditure', models.DateField()),
            ],
        ),
    ]
